#!/usr/bin/env python3
"""Generate the C catalogue and map-bounds headers used by the kiosk firmware.

Standard library only, no network access -- this is the build-time step run
by scripts/build.sh. The route/stop data itself is refreshed separately and
occasionally by tools/import_gtfs.py (which does need the network); this
script only turns the already-committed config/*.json into C headers.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
# Keep in sync with MAX_ROUTES/MAX_STOPS in include/catalog.h.
MAX_ROUTES = 512
MAX_STOPS = 128


def esc(value):
    return value.replace("\\", "\\\\").replace('"', '\\"')


def generate_catalog():
    routes = json.loads((ROOT / "config/routes.json").read_text(encoding="utf-8"))
    if len(routes) > MAX_ROUTES or any(len(r["stops"]) > MAX_STOPS for r in routes):
        raise SystemExit("Catalogue exceeds MAX_ROUTES/MAX_STOPS; increase limits in catalog.h first.")
    lines = ["/* Generated by tools/generate_catalog.py; do not edit. */", "static const Route ROUTES[] = {"]
    for r in routes:
        stops = ", ".join(
            '{"%s", "%s", "%s", "%s", %d, %d}'
            % (esc(s[0]), esc(s[1]), esc(s[2]), esc(s[3]), s[4], s[5])
            for s in r["stops"]
        )
        lines.append(
            ' {"%s", "%s", "%s", "%s", "%s", %d, 0x%s, %d, {%s}},'
            % (
                esc(r["number"]),
                esc(r["name_en"]),
                esc(r["name_mr"]),
                esc(r["name_hi"]),
                esc(r["name_gu"]),
                r["region"],
                r["color"],
                len(r["stops"]),
                stops,
            )
        )
    lines += ["};", ""]
    (ROOT / "generated").mkdir(exist_ok=True)
    (ROOT / "generated/routes_generated.h").write_text("\n".join(lines), encoding="utf-8")


def generate_map_bounds():
    bounds = json.loads((ROOT / "config/map_bounds.json").read_text(encoding="utf-8"))
    lines = [
        "/* Generated by tools/generate_catalog.py; do not edit. */",
        "const MapBounds MAP_BOUNDS = {%r, %r, %r, %r, %d, %d};"
        % (
            bounds["lon_min"],
            bounds["lon_max"],
            bounds["lat_min"],
            bounds["lat_max"],
            bounds["image_width"],
            bounds["image_height"],
        ),
        "",
    ]
    (ROOT / "generated").mkdir(exist_ok=True)
    (ROOT / "generated/map_bounds_generated.h").write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    generate_catalog()
    generate_map_bounds()
